name: notes_on_image
description: A new Flutter project.
publish_to: 'none'
version: 1.2.14+1
environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_colorpicker: ^1.1.0
  intl: ^0.20.2
  image: ^4.5.4
  permission_handler: ^12.0.0+1
  zoom_widget: ^2.0.1
  device_info_plus: ^11.4.0
  path: ^1.9.1
  simple_speed_dial: ^0.1.7
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true