name: notes_on_image
description: A new Flutter project.
publish_to: 'none'
version: 1.2.5+1
environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  image: ^4.1.3
  permission_handler: ^11.1.0
  zoom_widget: ^2.0.1
  device_info_plus: ^9.1.1
  path: ^1.8.1
  simple_speed_dial: ^0.1.7
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.15.7


flutter:
  uses-material-design: true