name: notes_on_image
description: A new Flutter project.
publish_to: 'none'
version: 1.2.3+1
environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  image: ^3.0.8
  permission_handler: ^9.2.0
  zoom_widget: ^0.2.1
  device_info_plus: ^3.2.4
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.15.7


flutter:
  uses-material-design: true